/* eslint-disable @next/next/no-img-element */
"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { FiEdit2, FiPlus, FiTrash2, FiUploadCloud } from "react-icons/fi";
import { ConfirmDialog, Feedback, Modal, PageHeader, Panel, PanelHeader, SearchBox, StatusBadge, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/AdminUI";
import { fetchAdminJSON, postFormData } from "@/lib/admin/fetch";
import type { AdminGalleryItem, GalleryKind } from "@/lib/admin/types";
import { GALLERY_CATEGORIES } from "@/data/galleryCategories";
const CATEGORIES = GALLERY_CATEGORIES.filter(
  (item): item is (typeof GALLERY_CATEGORIES)[number] & { value: NonNullable<(typeof GALLERY_CATEGORIES)[number]["value"]> } => Boolean(item.value),
);

export default function AdminGalleryPage() {
  const [rows, setRows] = useState<AdminGalleryItem[]>([]); const [search, setSearch] = useState(""); const [kind, setKind] = useState<GalleryKind | "">(""); const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<AdminGalleryItem | null>(null); const [deleting, setDeleting] = useState<AdminGalleryItem | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await fetchAdminJSON<{ items: AdminGalleryItem[] }>("/api/admin/gallery"); if (result.state === "success" && result.data) { setRows(result.data.items); setError(""); } else setError(result.error?.detail || result.message || "Unable to load gallery."); setLoading(false); }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => (!kind || row.kind === kind) && `${row.title} ${row.category}`.toLowerCase().includes(search.toLowerCase())), [rows, search, kind]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const result = await postFormData("/api/admin/gallery", new FormData(form)); if (result.state === "success") { setAdding(false); setMessage("Media uploaded."); await load(); } else setError(result.error?.detail || result.message || "Unable to upload media."); setBusy(false); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setBusy(true); const data = new FormData(event.currentTarget); const result = await fetchAdminJSON(`/api/admin/gallery/${editing.id}`, { method: "PATCH", body: JSON.stringify({ title: String(data.get("title") || ""), category: String(data.get("category")), isPublished: data.get("isPublished") === "true", displayOrder: Number(data.get("displayOrder") || 0) }) }); if (result.state === "success") { setEditing(null); setMessage("Gallery item updated."); await load(); } else setError(result.error?.detail || result.message || "Unable to update media."); setBusy(false); }
  async function remove() { if (!deleting) return; setBusy(true); const result = await fetchAdminJSON(`/api/admin/gallery/${deleting.id}`, { method: "DELETE" }); if (result.state === "success") { setDeleting(null); setMessage("Gallery item deleted."); await load(); } else setError(result.error?.detail || result.message || "Unable to delete media."); setBusy(false); }
  return <div><PageHeader title="Gallery" description="Upload, organize, publish, and remove website media." action={<button className={buttonClass} onClick={() => setAdding(true)}><FiPlus /> Add media</button>} /><Feedback error={error} message={message} /><Panel><PanelHeader title="Media library" subtitle={`${filtered.length} items`} action={<div className="flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search media…" /><select className={`${inputClass} sm:w-36`} value={kind} onChange={(e) => setKind(e.target.value as GalleryKind | "")}><option value="">All media</option><option>IMAGE</option><option>VIDEO</option></select></div>} /><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{filtered.map((row) => <article key={row.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative aspect-[4/3] overflow-hidden bg-slate-100"><img src={row.poster || row.src} alt={row.title || "Gallery media"} className="h-full w-full object-cover" /><div className="absolute left-3 top-3"><StatusBadge value={row.isPublished ? "PUBLISHED" : "DRAFT"} /></div></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.title || "Untitled"}</p><p className="mt-1 text-xs text-slate-400">{row.category} · {row.kind}</p></div><div className="flex shrink-0"><button aria-label="Edit media" onClick={() => setEditing(row)} className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><FiEdit2 /></button><button aria-label="Delete media" onClick={() => setDeleting(row)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><FiTrash2 /></button></div></div></div></article>)}{loading ? <p className="col-span-full py-12 text-center text-sm text-slate-400">Loading gallery…</p> : null}{!loading && !filtered.length ? <p className="col-span-full py-12 text-center text-sm text-slate-400">No media found.</p> : null}</div></Panel>
    {adding ? <Modal title="Upload media" onClose={() => setAdding(false)}><form onSubmit={upload} className="space-y-4"><label className="grid cursor-pointer place-items-center rounded-xl border-2 border-dashed border-slate-200 p-8 text-center hover:border-[#e63946]"><FiUploadCloud className="h-8 w-8 text-[#e63946]" /><span className="mt-2 text-sm font-medium">Choose image or video</span><input name="file" type="file" accept="image/*,video/*" required className="mt-3 text-xs" /></label><input name="title" placeholder="Title" className={inputClass} /><div className="grid grid-cols-2 gap-3"><select name="kind" className={inputClass}><option>IMAGE</option><option>VIDEO</option></select><select name="category" required className={inputClass}>{CATEGORIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select name="orientation" className={inputClass}><option value="landscape">Landscape</option><option value="portrait">Portrait</option><option value="square">Square</option></select><input name="mediaType" placeholder="Media type (optional)" className={inputClass} /></div><div className="flex justify-end gap-3"><button type="button" className={secondaryButtonClass} onClick={() => setAdding(false)}>Cancel</button><button disabled={busy} className={buttonClass}>{busy ? "Uploading…" : "Upload"}</button></div></form></Modal> : null}
    {editing ? <Modal title="Edit media" onClose={() => setEditing(null)}><form onSubmit={save} className="space-y-4"><input name="title" defaultValue={editing.title || ""} placeholder="Title" className={inputClass} /><select name="category" defaultValue={editing.category} className={inputClass}>{CATEGORIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input name="displayOrder" type="number" defaultValue={editing.displayOrder} className={inputClass} /><select name="isPublished" defaultValue={String(editing.isPublished)} className={inputClass}><option value="true">Published</option><option value="false">Draft</option></select><div className="flex justify-end gap-3"><button type="button" className={secondaryButtonClass} onClick={() => setEditing(null)}>Cancel</button><button disabled={busy} className={buttonClass}>{busy ? "Saving…" : "Save changes"}</button></div></form></Modal> : null}
    {deleting ? <ConfirmDialog title="Delete media" description="Delete this gallery item and its Cloudinary asset? This action cannot be undone." busy={busy} onCancel={() => setDeleting(null)} onConfirm={() => void remove()} /> : null}
  </div>;
}
