"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { FiEdit2, FiPlus, FiSlash } from "react-icons/fi";
import { ConfirmDialog, Feedback, Modal, PageHeader, Panel, PanelHeader, SearchBox, StatusBadge, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/AdminUI";
import { fetchAdminJSON } from "@/lib/admin/fetch";
import type { AdminUser } from "@/lib/admin/types";

export default function AdminUsersPage() {
  const [rows, setRows] = useState<AdminUser[]>([]); const [search, setSearch] = useState(""); const [role, setRole] = useState<"USER" | "ADMIN" | "">(""); const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<AdminUser | null>(null); const [deactivating, setDeactivating] = useState<AdminUser | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await fetchAdminJSON<{ items: AdminUser[] }>(`/api/admin/users${role ? `?role=${role}` : ""}`); if (result.state === "success" && result.data) { setRows(result.data.items); setError(""); } else setError(result.error?.detail || result.message || "Unable to load users."); setLoading(false); }, [role]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => `${row.fullName} ${row.username} ${row.email} ${row.phone}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  async function save(roleValue: "USER" | "ADMIN", isActive: boolean) { if (!editing) return; setBusy(true); const result = await fetchAdminJSON("/api/admin/users", { method: "PATCH", body: JSON.stringify({ id: editing.id, role: roleValue, isActive }) }); if (result.state === "success") { setEditing(null); setMessage("User updated."); await load(); } else setError(result.error?.detail || result.message || "Unable to update user."); setBusy(false); }
  async function deactivate() { if (!deactivating) return; setBusy(true); const result = await fetchAdminJSON(`/api/admin/users?id=${encodeURIComponent(deactivating.id)}`, { method: "DELETE" }); if (result.state === "success") { setDeactivating(null); setMessage("User deactivated and active sessions revoked."); await load(); } else setError(result.error?.detail || result.message || "Unable to deactivate user."); setBusy(false); }
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); const result = await fetchAdminJSON("/api/admin/users", { method: "POST", body: JSON.stringify({ email: data.get("email"), username: data.get("username"), password: data.get("password"), fullName: data.get("fullName") || undefined, phone: data.get("phone") || undefined, role: data.get("role") }) }); if (result.state === "success") { setAdding(false); setMessage("User account created."); await load(); } else setError(result.error?.detail || result.message || "Unable to create user."); setBusy(false); }
  return <div><PageHeader title="Users" description="View accounts, manage access levels, and revoke user sessions." action={<button className={buttonClass} onClick={() => setAdding(true)}><FiPlus /> Add user</button>} /><Feedback error={error} message={message} /><Panel><PanelHeader title="Registered users" subtitle={`${filtered.length} accounts`} action={<div className="flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search users…" /><select className={`${inputClass} sm:w-36`} value={role} onChange={(e) => setRole(e.target.value as typeof role)}><option value="">All roles</option><option>USER</option><option>ADMIN</option></select></div>} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["User", "Contact", "Role", "Activity", "Status", "Actions"].map((item) => <th key={item} className="px-5 py-3 font-semibold">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((row) => <tr key={row.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{(row.username || row.fullName || "U").slice(0, 2).toUpperCase()}</span><div><p className="font-medium text-slate-800">{row.username || row.fullName || "User"}</p><p className="text-xs text-slate-400">Joined {new Date(row.createdAt).toLocaleDateString()}</p></div></div></td><td className="px-5 py-4"><p className="text-slate-600">{row.email || "—"}</p><p className="text-xs text-slate-400">{row.phone || "No mobile"}</p></td><td className="px-5 py-4"><span className="text-xs font-semibold">{row.role}</span></td><td className="px-5 py-4 text-xs text-slate-500">{row.bookings} bookings · {row.reviews} reviews</td><td className="px-5 py-4"><StatusBadge value={row.isActive ? "ACTIVE" : "INACTIVE"} /></td><td className="px-5 py-4"><div className="flex gap-1"><button aria-label="Edit user" className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-blue-600" onClick={() => setEditing(row)}><FiEdit2 /></button>{row.isActive ? <button aria-label="Deactivate user" className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={() => setDeactivating(row)}><FiSlash /></button> : null}</div></td></tr>)}</tbody></table>{loading ? <p className="py-14 text-center text-sm text-slate-400">Loading users…</p> : null}{!loading && !filtered.length ? <p className="py-14 text-center text-sm text-slate-400">No users found.</p> : null}</div></Panel>
    {adding ? <Modal title="Add user" onClose={() => setAdding(false)}><form onSubmit={create} className="space-y-4"><input name="fullName" minLength={2} maxLength={100} placeholder="Full name (optional)" className={inputClass} /><input name="email" required type="email" placeholder="Email address" className={inputClass} /><input name="username" required minLength={3} maxLength={30} pattern="[A-Za-z0-9._-]+" placeholder="Username" className={inputClass} /><input name="phone" type="tel" placeholder="Mobile number (optional)" className={inputClass} /><input name="password" required type="password" minLength={12} maxLength={128} placeholder="Temporary password (12+ characters)" className={inputClass} /><select name="role" className={inputClass}><option>USER</option><option>ADMIN</option></select><div className="flex justify-end gap-3"><button type="button" className={secondaryButtonClass} onClick={() => setAdding(false)}>Cancel</button><button disabled={busy} className={buttonClass}>{busy ? "Creating…" : "Create user"}</button></div></form></Modal> : null}
    {editing ? <UserModal user={editing} busy={busy} onClose={() => setEditing(null)} onSave={save} /> : null}
    {deactivating ? <ConfirmDialog title="Deactivate user" description={`Deactivate ${deactivating.username || deactivating.email || "this account"}? All existing sessions will be revoked. Their historical bookings and reviews will be preserved.`} busy={busy} onCancel={() => setDeactivating(null)} onConfirm={() => void deactivate()} /> : null}
  </div>;
}

function UserModal({ user, busy, onClose, onSave }: { user: AdminUser; busy: boolean; onClose: () => void; onSave: (role: "USER" | "ADMIN", active: boolean) => void }) { const [role, setRole] = useState(user.role); const [active, setActive] = useState(user.isActive); return <Modal title="Manage user" onClose={onClose}><div className="rounded-lg bg-slate-50 p-4"><p className="font-medium">{user.username || user.fullName || "User"}</p><p className="mt-1 text-xs text-slate-500">{user.email}</p></div><label className="mt-5 block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">Role</span><select value={role} onChange={(e) => setRole(e.target.value as "USER" | "ADMIN")} className={inputClass}><option>USER</option><option>ADMIN</option></select></label><label className="mt-4 flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} className="accent-[#e63946]" /> Account is active</label><div className="mt-6 flex justify-end gap-3"><button className={secondaryButtonClass} onClick={onClose}>Cancel</button><button disabled={busy} className={buttonClass} onClick={() => onSave(role, active)}>{busy ? "Saving…" : "Save changes"}</button></div></Modal>; }
