"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { FiMail, FiTrash2 } from "react-icons/fi";
import { ConfirmDialog, Feedback, Modal, PageHeader, Panel, PanelHeader, SearchBox, StatusBadge, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/AdminUI";
import { fetchAdminJSON } from "@/lib/admin/fetch";
import type { AdminContact, ContactStatus } from "@/lib/admin/types";

const STATUSES: ContactStatus[] = ["NEW", "CONTACTED", "CLOSED"];

export default function AdminMessagesPage() {
  const [rows, setRows] = useState<AdminContact[]>([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<ContactStatus | "">("");
  const [selected, setSelected] = useState<AdminContact | null>(null);
  const [deleting, setDeleting] = useState<AdminContact | null>(null);
  const [reply, setReply] = useState("");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await fetchAdminJSON<{ items: AdminContact[] }>(`/api/admin/contacts${status ? `?status=${status}` : ""}`); if (result.state === "success" && result.data) { setRows(result.data.items); setError(""); } else setError(result.error?.detail || result.message || "Unable to load messages."); setLoading(false); }, [status]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => `${row.name} ${row.email} ${row.phone} ${row.eventType} ${row.location} ${row.specialRequest}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  async function update(nextStatus: ContactStatus) { if (!selected) return; setBusy(true); const result = await fetchAdminJSON("/api/admin/contacts", { method: "PATCH", body: JSON.stringify({ id: selected.id, status: nextStatus, userEmail: selected.email || undefined, adminReply: reply || undefined }) }); if (result.state === "success") { setSelected(null); setReply(""); setMessage("Message updated."); await load(); } else setError(result.error?.detail || result.message || "Unable to update message."); setBusy(false); }
  async function remove() { if (!deleting) return; setBusy(true); const result = await fetchAdminJSON(`/api/admin/contacts?id=${encodeURIComponent(deleting.id)}`, { method: "DELETE" }); if (result.state === "success") { setDeleting(null); setMessage("Message deleted."); await load(); } else setError(result.error?.detail || result.message || "Unable to delete message."); setBusy(false); }
  return <div><PageHeader title="Messages" description="Read customer enquiries, reply by email, and manage their status." /><Feedback error={error} message={message} /><Panel><PanelHeader title="Contact enquiries" subtitle={`${filtered.length} messages`} action={<div className="flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search messages…" /><select className={`${inputClass} sm:w-40`} value={status} onChange={(e) => setStatus(e.target.value as ContactStatus | "")}><option value="">All statuses</option>{STATUSES.map((item) => <option key={item}>{item}</option>)}</select></div>} /><div className="divide-y divide-slate-100">{filtered.map((row) => <article key={row.id} className="grid gap-4 px-5 py-4 hover:bg-slate-50/70 md:grid-cols-[minmax(180px,.7fr)_1.5fr_auto] md:items-center"><div><p className="font-medium text-slate-800">{row.name || "Customer"}</p><p className="mt-1 text-xs text-slate-400">{row.email || row.phone}</p></div><button type="button" className="min-w-0 text-left" onClick={() => { setSelected(row); setReply(""); }}><p className="truncate text-sm font-medium text-slate-700">{row.eventType} · {row.location}</p><p className="mt-1 line-clamp-1 text-xs text-slate-400">{row.specialRequest || "No additional message"}</p></button><div className="flex items-center justify-between gap-3 md:justify-end"><StatusBadge value={row.status} /><button aria-label="Delete message" onClick={() => setDeleting(row)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><FiTrash2 /></button></div></article>)}{loading ? <p className="py-14 text-center text-sm text-slate-400">Loading messages…</p> : null}{!loading && !filtered.length ? <p className="py-14 text-center text-sm text-slate-400">No messages found.</p> : null}</div></Panel>
    {selected ? <Modal title="Customer message" onClose={() => setSelected(null)}><div className="space-y-4"><div className="rounded-lg bg-slate-50 p-4"><p className="text-sm font-semibold">{selected.name || "Customer"}</p><p className="mt-1 text-xs text-slate-500">{selected.email} · {selected.phone}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-400">Event</dt><dd>{selected.eventType}</dd></div><div><dt className="text-xs text-slate-400">Event date</dt><dd>{new Date(selected.eventDate).toLocaleDateString()}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-slate-400">Location</dt><dd>{selected.location}</dd></div></dl></div><div><p className="text-xs font-semibold text-slate-500">MESSAGE</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{selected.specialRequest || "No additional message."}</p></div><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">Email reply (optional)</span><textarea value={reply} onChange={(e) => setReply(e.target.value)} rows={4} className={inputClass} placeholder="Write a response…" /></label><div className="flex flex-wrap justify-end gap-2"><button className={secondaryButtonClass} onClick={() => setSelected(null)}>Cancel</button>{STATUSES.map((item) => <button key={item} disabled={busy} className={item === "CONTACTED" ? buttonClass : secondaryButtonClass} onClick={() => void update(item)}><FiMail /> {item}</button>)}</div></div></Modal> : null}
    {deleting ? <ConfirmDialog title="Delete message" description="Permanently delete this contact enquiry? This action cannot be undone." busy={busy} onCancel={() => setDeleting(null)} onConfirm={() => void remove()} /> : null}
  </div>;
}
