"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { FiCheck, FiStar, FiTrash2, FiX } from "react-icons/fi";
import { ConfirmDialog, Feedback, Modal, PageHeader, Panel, PanelHeader, SearchBox, StatusBadge, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/AdminUI";
import { fetchAdminJSON } from "@/lib/admin/fetch";
import type { AdminReview, ReviewStatus } from "@/lib/admin/types";
const STATUSES: ReviewStatus[] = ["PENDING", "APPROVED", "REJECTED"];

export default function AdminReviewsPage() {
  const [rows, setRows] = useState<AdminReview[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState<ReviewStatus | "">(""); const [selected, setSelected] = useState<AdminReview | null>(null); const [deleting, setDeleting] = useState<AdminReview | null>(null); const [reply, setReply] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await fetchAdminJSON<{ items: AdminReview[] }>(`/api/admin/reviews${status ? `?status=${status}` : ""}`); if (result.state === "success" && result.data) { setRows(result.data.items); setError(""); } else setError(result.error?.detail || result.message || "Unable to load reviews."); setLoading(false); }, [status]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => `${row.user.name} ${row.user.email} ${row.message}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  async function decide(nextStatus: "APPROVED" | "REJECTED") { if (!selected) return; setBusy(true); const result = await fetchAdminJSON("/api/admin/reviews", { method: "PATCH", body: JSON.stringify({ id: selected.id, status: nextStatus, adminReply: reply || undefined, userEmail: selected.user.email || undefined }) }); if (result.state === "success") { setSelected(null); setReply(""); setMessage(`Review ${nextStatus.toLowerCase()}.`); await load(); } else setError(result.error?.detail || result.message || "Unable to update review."); setBusy(false); }
  async function remove() { if (!deleting) return; setBusy(true); const result = await fetchAdminJSON(`/api/admin/reviews?id=${encodeURIComponent(deleting.id)}`, { method: "DELETE" }); if (result.state === "success") { setDeleting(null); setMessage("Review deleted."); await load(); } else setError(result.error?.detail || result.message || "Unable to delete review."); setBusy(false); }
  return <div><PageHeader title="Reviews" description="Moderate customer feedback before it appears on the website." /><Feedback error={error} message={message} /><Panel><PanelHeader title="Customer reviews" subtitle={`${filtered.length} reviews`} action={<div className="flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search reviews…" /><select className={`${inputClass} sm:w-40`} value={status} onChange={(e) => setStatus(e.target.value as ReviewStatus | "")}><option value="">All statuses</option>{STATUSES.map((item) => <option key={item}>{item}</option>)}</select></div>} /><div className="grid gap-4 p-5 lg:grid-cols-2">{filtered.map((row) => <article key={row.id} className="rounded-xl border border-slate-200 p-4 transition hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-800">{row.user.name || row.user.phone || "Customer"}</p><p className="mt-1 text-xs text-slate-400">{row.user.email || "No email"}</p></div><StatusBadge value={row.status} /></div><div className="mt-3 flex gap-0.5 text-amber-400">{Array.from({ length: 5 }, (_, index) => <FiStar key={index} className={index < row.rating ? "fill-current" : "text-slate-200"} />)}</div><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{row.message}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs text-slate-400">{new Date(row.createdAt).toLocaleDateString()}</span><div className="flex gap-1"><button className={secondaryButtonClass} onClick={() => { setSelected(row); setReply(row.adminReply || ""); }}>Review</button><button aria-label="Delete review" onClick={() => setDeleting(row)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><FiTrash2 /></button></div></div></article>)}{loading ? <p className="col-span-full py-10 text-center text-sm text-slate-400">Loading reviews…</p> : null}{!loading && !filtered.length ? <p className="col-span-full py-10 text-center text-sm text-slate-400">No reviews found.</p> : null}</div></Panel>
    {selected ? <Modal title="Moderate review" onClose={() => setSelected(null)}><p className="text-sm leading-6 text-slate-700">{selected.message}</p><label className="mt-5 block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">Reply or moderation note</span><textarea value={reply} onChange={(e) => setReply(e.target.value)} rows={4} className={inputClass} /></label><div className="mt-5 flex justify-end gap-2"><button disabled={busy} className={secondaryButtonClass} onClick={() => void decide("REJECTED")}><FiX /> Reject</button><button disabled={busy} className={buttonClass} onClick={() => void decide("APPROVED")}><FiCheck /> Approve</button></div></Modal> : null}
    {deleting ? <ConfirmDialog title="Delete review" description="Permanently delete this review? It will immediately disappear from the public website if published." busy={busy} onCancel={() => setDeleting(null)} onConfirm={() => void remove()} /> : null}
  </div>;
}
